#! /bin/sh

# Generate an HTML index for all the subdirectories

for i in `find . -name CVS -prune -o -type d -print` ; do
    if [ $i == "." ]; then
        continue
    fi
    cat > $i/index.html <<EOF
<HTML>
<!-- This file is automatically generated. Do not edit! -->
<HEAD>
<TITLE>RedBoot binaries and support files for platform `echo $i | sed 's#.*/##g'`</TITLE>
</HEAD>

<!--#include virtual="/ecos/include/header.html"-->

<h1>RedBoot binaries and support files for `cat $i/platformname`</h1>
<HR noshade SIZE=3>
<ul>
EOF
    for j in $i/* ; do
        SHORTNAME=`echo $j | sed 's#.*/##g'`
        if [ $SHORTNAME == "CVS" -o $SHORTNAME == index.html -o $SHORTNAME == platformname ]; then
            continue
        fi
        if [ -d $j ]; then
            cat >> $i/index.html <<EOF
<li><a href="$SHORTNAME">$SHORTNAME</a></li>
EOF
        else
            SIZE=`ls -l $j | awk '{print $5}'`
            SIZEK=`echo "$SIZE/1024" | bc`
            cat >> $i/index.html <<EOF
<li><a href="$SHORTNAME">$SHORTNAME</a> ($SIZEK Kbytes)</li>
EOF
        fi
    done
    cat >> $i/index.html <<EOF
</ul>
<HR noshade SIZE=3>
<!--#include virtual="/ecos/include/footer.html"-->
EOF

done

cat > index.html <<EOF
<HTML>
<!-- This file is automatically generated. Do not edit! -->
<HEAD>
<TITLE>RedBoot binaries and support files</TITLE>
</HEAD>

<!--#include virtual="/ecos/include/header.html"-->

<h1>RedBoot binaries and support files</h1>
<HR noshade SIZE=3>
<ul>
EOF
rm -f index.html.tmp
for i in */platformname ; do
     cat >> index.html.tmp <<EOF
<li><a href="`dirname $i`/"> `cat $i`</a></li>
EOF
done
sort -f +2 < index.html.tmp >> index.html
rm -f index.html.tmp
cat >> index.html <<EOF
</ul>
<HR noshade SIZE=3>
<!--#include virtual="/ecos/include/footer.html"-->
EOF
